checks:
  javascript: true
build:
  nodes:
    analysis:
      tests:
        override:
          - 
            command: |
              nvm install 20.5.1
              nvm use 20.5.1
              cd server
              npm install
              npm run test
            coverage:
              file: 'server/coverage/clover.xml'
              format: 'clover'
