checks:
    javascript: true
filter:
    excluded_paths: [test/*]
build:
    nodes:
        analysis:
            tests:
                override:
                    - js-scrutinizer-run
        tests: true
        coverage:
              tests:
                override:
                  - title: "Generate code coverage"
                    command: echo "No test command needed"
                    coverage:
                      file: clover/clover.xml
                      format: clover
    root_path: ./server/
artifacts:
    paths:
        - clover/clover.xml
