checks:
  javascript: true

build:
  environment:
    variables:
      DB_NAME: "bikes"
      DB_ROOT_PASSWORD: "root"
      DB_USER: "root"
      DB_SERVICE_NAME: "localhost"
      TEST_DB_NAME: "test"
      TEST_SERVICE_NAME: "localhost"
      JWT_SECRET: "5d9e0b327c674d279771aed90ad876165d9e0b327c674d279771aed90ad87616"
  services:
    mariadb:
      image: mariadb:10.11.6
      # ports: 3306:3306
      env:
        MARIADB_ROOT_PASSWORD: "root"
        MARIADB_DATABASE: "test"

  nodes:
    analysis:
      tests:
        override:
          - 
            command: |
              nvm install 16
              nvm use --delete-prefix v16
              cd server
              npm install

              echo "Waiting for MariaDB..."
              while ! mysqladmin ping -h"$DB_SERVICE_NAME" --silent; do
                  sleep 5
              done

              mysql -h $DB_SERVICE_NAME -u $DB_USER -p$DB_ROOT_PASSWORD $TEST_DB_NAME < ../mariadb/docker/setup-test.sql

              npm run test
            coverage:
              file: 'server/coverage/clover.xml'
              format: 'clover'
