build:
  nodes:
    primary:
      environment:
        variables:
          DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
          DB_SERVICE_NAME: mariadb-bikes 
          TEST_SERVICE_NAME: mariadb-test 
          DB_NAME: bikes
          TEST_DB_NAME: test
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      dependencies:
        before:
          - sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          - sudo chmod +x /usr/local/bin/docker-compose
        override:
          - docker-compose up -d

      tests:
        override:
          - docker-compose exec server npm run test

