checks:
  javascript: true

build:
  environment:
    variables:
      DB_NAME: "bikes"
      DB_ROOT_PASSWORD: "root"
      DB_USER: "root"
      DB_SERVICE_NAME: "127.0.0.1"
      TEST_DB_NAME: "test"
      TEST_SERVICE_NAME: "127.0.0.1"
      JWT_SECRET: "5d9e0b327c674d279771aed90ad876165d9e0b327c674d279771aed90ad87616"
  services:
    mariadb:
      image: mariadb:10.11.6
      environment:
        MYSQL_ROOT_PASSWORD: "root"
        MYSQL_DATABASE: "test"

  nodes:
    analysis:
      tests:
        override:
          - 
            command: |
              nvm install 16
              nvm use --delete-prefix v16
              cd server
              npm install

              mysql -h $DB_SERVICE_NAME -u $DB_USER -p$DB_ROOT_PASSWORD $DB_NAME < ../mariadb/docker/setup-test.sql

              npm run test
            coverage:
              file: 'server/coverage/clover.xml'
              format: 'clover'
