checks:
  javascript: true
build:
  environment:
    node: '18.x'
  tests:
    override:
      - 
        command: 'cd server && npm install && npm run test'
        coverage:
          file: 'server/coverage/clover.xml'
          format: 'clover'
