build:
  nodes:
    docker-build:
      environment:
        variables:
          DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
          DB_SERVICE_NAME: mariadb-bikes 
          TEST_SERVICE_NAME: mariadb-test 
          DB_NAME: bikes
          TEST_DB_NAME: test
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        docker: true
  


      dependencies:
        override:
          - docker-compose up -d

      tests:
        override:
          - docker-compose exec server npm install
          - docker-compose exec server npm run test