version: "3"
services:
  mariadb:
    image: "mariadb:latest"
    container_name: "mariadb"
    working_dir: "/docker-entrypoint-initdb.d"
    volumes:
      - ./mariadb/:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
    healthcheck: # TODO check more in detail what healthcheck times does (start_period, interval etc.)
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    restart: 
        "always"

  # server:
  #   build:
  #       context: . # Path needs to be changed when directory structure changes
  #       dockerfile: Dockerfile # Not necessary as long as dockerfile is named Dockerfile
  #   container_name: "vteam-server"
  #   volumes: # Add potential volumes
  #   ports: # Add ports in- and outside of container
  #   restart: "always"
