version: "3"
services:
  mariadb-bikes:
    image: "mariadb:latest"
    container_name: "mariadb-bikes"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: bikes
    volumes:
      - "./mariadb/:/docker-entrypoint-initdb.d/"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    restart: "always"
    command: "--init-file /docker-entrypoint-initdb.d/setup-bikes.sql"

  mariadb-test:
    image: "mariadb:latest"
    container_name: "mariadb-test"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: test
    volumes:
      - "./mariadb/:/docker-entrypoint-initdb.d/"
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    restart: "always"
    command: "--init-file /docker-entrypoint-initdb.d/setup-test.sql"

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: "server"
    environment:
      DB_HOST: ${DB_SERVICE_NAME}
      DB_TEST_HOST: ${TEST_SERVICE_NAME}
      DB_PORT: "3306"
      DB_USER: "root"
      DB_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_DATABASE: ${DB_NAME}
      TEST_DATABASE: ${TEST_DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./server/package.json:/server/package.json
      - ./server/package-lock.json:/server/package-lock.json
      - ./server/mocha.json:/server/mocha.json
      - ./server/app.js:/server/app.js
      - ./server/routes/:/server/routes/
      - ./server/test/:/server/test/
      - ./server/src/:/server/src/
      - ./server/.eslintignore:/server/.eslintignore
      - ./server/.eslintrc.json:/server/.eslintrc.json
      - ./server/.prettierignore:/server/.prettierignore
    ports:
      - "1337:1337"
    depends_on:
      - mariadb-bikes
      - mariadb-test
    restart: "always"




  # server:
  #   build:
  #       context: . # Path needs to be changed when directory structure changes
  #       dockerfile: Dockerfile # Not necessary as long as dockerfile is named Dockerfile
  #   container_name: "vteam-server"
  #   volumes: # Add potential volumes
  #   ports: # Add ports in- and outside of container
  #   restart: "always"
