version: "3"
services:
  mariadb-bikes:
    image: "mariadb:10.11.6"
    container_name: "mariadb-bikes"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: bikes
    volumes:
      - "./mariadb/:/mariadb/"
      - "./mariadb/docker/:/docker-entrypoint-initdb.d/"
      # - "./my.cnf:/etc/mysql/my.cnf"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USER}", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: "always"
    # command: "--init-file /docker-entrypoint-initdb.d/setup-bikes-docker.sql"

  mariadb-test:
    image: "mariadb:10.11.6"
    container_name: "mariadb-test"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: test
      MYSQLD_LOCAL_INFILE: "1"
    volumes:
      - "./mariadb/:/mariadb/"
      - "./mariadb/docker/:/docker-entrypoint-initdb.d/"
      # - "./my.cnf:/etc/mysql/my.cnf"
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USER}", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: "always"
    # command: "--init-file /docker-entrypoint-initdb.d/setup-test-docker.sql"

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: "server"
    environment:
      DB_HOST: ${DB_SERVICE_NAME}
      DB_TEST_HOST: ${TEST_SERVICE_NAME}
      DB_PORT: "3306"
      DB_USER: "root"
      DB_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_DATABASE: ${DB_NAME}
      TEST_DATABASE: ${TEST_DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./server/package.json:/server/package.json
      - ./server/package-lock.json:/server/package-lock.json
      - ./server/mocha.json:/server/mocha.json
      - ./server/app.js:/server/app.js
      - ./server/server.js:/server/server.js
      - ./server/routes/:/server/routes/
      - ./server/test/:/server/test/
      - ./server/src/:/server/src/
      - ./server/.eslintignore:/server/.eslintignore
      - ./server/.eslintrc.json:/server/.eslintrc.json
      - ./server/.prettierignore:/server/.prettierignore
    ports:
      - "1337:1337"
    depends_on:
      mariadb-bikes:
        condition: service_healthy
      mariadb-test:
        condition: service_healthy
    restart: "always"




  # server:
  #   build:
  #       context: . # Path needs to be changed when directory structure changes
  #       dockerfile: Dockerfile # Not necessary as long as dockerfile is named Dockerfile
  #   container_name: "vteam-server"
  #   volumes: # Add potential volumes
  #   ports: # Add ports in- and outside of container
  #   restart: "always"
