# Build stage
FROM node:20-alpine3.18 as build

WORKDIR /server

COPY ./server .

RUN npm install

# Deploy stage
FROM node:20-alpine3.18 as deploy

COPY --from=build /server/package.json ./

COPY --from=build /server/package-lock.json ./

RUN npm ci --omit dev

COPY --from=build /server ./

EXPOSE 1337

ENTRYPOINT [ "node", "-r" , "dotenv/config", "server.js"]